### ISSUE TITLE
FRITZ!OS 7.50 Support / Message loop after update

### ISSUE THREAD

**Issue by blueicehaller** [DrMichael/FritzCall#5]
Hi @DrMichael,
unfortunately [Github Discussions](https://docs.github.com/de/discussions) is not active in your repository. Therefore I create this issue.

I updated the firmware of the FRITZ!Box 7590 from 7.29 to the new [FRITZ!OS 7.50](https://avm.de/produkte/fritzos/fritzos-750/).
Then I installed / updated enigma2-plugin-extensions-fritzcall to the latest [release](../releases)

Now I got this Error and stuck in a loop of the 3 Messages after restart of enigma2:
```
Informationen (#)
Verbindung zur FRITZ!Box fehlgeschlagen
(An error occured while connecting: [Failure instance: Taceback (failure with no frames): <type
'exceptions.AttributeError'>: 'module' object has no attribute 'ensure_text'
].)
neuer Versuch...
```
```
Informationen (#)
Verbinde mit FRITZ!Box...
```
```
Informationen (#)
Verbunden mit FRITZ!Box!
```

To break out of the loop I can move the folder away and restart enigma2:
`/usr/lib/enigma2/python/Plugins/Extensions/FritzCall/`

Install / Update Log
```
root@wohnzimmer-receiver:~# opkg install enigma2-plugin-extensions-fritzcall_20220526-rev1620_all.ipk
Upgrading enigma2-plugin-extensions-fritzcall from 6.3+git6863+3570ed5-r0 to 99999:20220526-rev1620 on root.
Installing libpython3.5m1.0 (3.5.6) on root.
Downloading http://feeds2.mynonpublic.com/6.3/inihdp/mips32el/libpython3.5m1.0_3.5.6-r1.0_mips32el.ipk.
Installing python3-core (3.5.6) on root.
Downloading http://feeds2.mynonpublic.com/6.3/inihdp/mips32el/python3-core_3.5.6-r1.0_mips32el.ipk.
Installing python3-html (3.5.6) on root.
Downloading http://feeds2.mynonpublic.com/6.3/inihdp/mips32el/python3-html_3.5.6-r1.0_mips32el.ipk.
Installing python3-json (3.5.6) on root.
Downloading http://feeds2.mynonpublic.com/6.3/inihdp/mips32el/python3-json_3.5.6-r1.0_mips32el.ipk.
Installing enigma2-plugin-extensions-fritzcall (20220526) on root.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/nrzuname.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/ca/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/cs/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/FritzCallFBF.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/ro/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/ldif.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/pl/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/lt/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/he/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/fy/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/el/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/maintainer.info.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/pt_BR/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/th/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/hr/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/FritzLDIF.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/plugin.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/pt/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/fa/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/sv/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/uk/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/et/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/en_GB/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/sl/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/FritzOutlookCSV.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/ar/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/fi/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/hu/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/LICENSE.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/nb/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/fr/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/lv/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/FritzConnection.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/en/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/da/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/__init__.pyo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/sk/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/ru/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/bg/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/no/LC_MESSAGES/FritzCall.mo.
Removing obsolete file /usr/lib/enigma2/python/Plugins/Extensions/FritzCall/locale/is/LC_MESSAGES/FritzCall.mo.
Configuring libpython3.5m1.0.
Configuring python3-core.
Configuring python3-html.
Configuring python3-json.
Configuring enigma2-plugin-extensions-fritzcall.
Enigma2 muss neu gestartet werden
root@wohnzimmer-receiver:~#
```

I stopped enigma2 (init 4) and then I deleted these lines from `/etc/enigma2/settings`
```
config.plugins.FritzCall.enable=true
config.plugins.FritzCall.fritzphonebook=true
config.plugins.FritzCall.fwVersion=06.35
config.plugins.FritzCall.hostname=
config.plugins.FritzCall.lookup=true
config.plugins.FritzCall.muteOnCall=true
config.plugins.FritzCall.password=******
config.plugins.FritzCall.timeout=10
config.plugins.FritzCall.username=******
```
Then I started enigma2 (init 3).
Now FritzCall is reset to default.
After configuring and clicking green to save the settings, enigma2 crashed and [enigma2_crash_1670987317.log](https://github.com/DrMichael/FritzCall/files/10224051/enigma2_crash_1670987317.log) was created.

Then I changed the setting to disable FritzCall and clicking green to save the settings, enigma2 crashed again and [enigma2_crash_1670987368.log](https://github.com/DrMichael/FritzCall/files/10224059/enigma2_crash_1670987368.log) was created.

What do you need from my side to fix this issue?

Thank you in advance.

Best regards

**Comment by DrMichael** [comment]
The line numbers do not correspond to my sources. Could you send me your FritzConnection.py please.

**Comment by blueicehaller** [comment]
[FritzConnection.py.txt](https://github.com/DrMichael/FritzCall/files/10235996/FritzConnection.py.txt)

**Comment by DrMichael** [comment]
Try this one... It appears to be an issue with the six module....

[enigma2-plugin-extensions-fritzcall_20221215-rev1631_all.zip](https://github.com/DrMichael/FritzCall/files/10236313/enigma2-plugin-extensions-fritzcall_20221215-rev1631_all.zip)

**Comment by blueicehaller** [comment]
Now I get this Error again:
```
Informationen (#)
Verbindung zur FRITZ!Box fehlgeschlagen
(An error occured while connecting: [Failure instance: Taceback (failure with no frames): <type
'exceptions.AttributeError'>: 'module' object has no attribute 'ensure_text'
].)
neuer Versuch...
```

**Comment by DrMichael** [comment]
What gives `opkg list-installed | grep six` on the box?
Which firmware is it running?

**Comment by blueicehaller** [comment]
```
root@wohnzimmer-receiver:~# opkg list-installed | grep six
python-six - 1.11.0-r0
root@wohnzimmer-receiver:~# opkg list-installed | grep fritz
enigma2-plugin-extensions-fritzcall - 99999:20221215-rev1631
```
```
Receiver
Marke & Modell: 	GI LX-3
Chipsatz (Frontprozessor-Version): 	Broadcom 7424 (20038)
Hauptspeicher: 	930144 kB frei / 1154756 kB insgesamt
Receiver-Laufzeit: 	10d 12:04
Software
OE-System: 	OE-Alliance 4.3
Firmware-Version: 	OpenATV 6.3.0 (2020-02-18)
Kernel / Treiber: 	3.14.2 / 20160120
```

**Comment by DrMichael** [comment]
OpenATV 6.3 is almost two years old... 

Dependancy on python-six is in the ipk.

**Comment by blueicehaller** [comment]
Never change a running system 😁 

Is the dependency based on a min. Version?

**Comment by blueicehaller** [comment]
I just want to inform you what on my other Receiver it works with `python-six - 1.12.0-r0` 👍 .

```
root@schlafzimmer-receiver:~# opkg list-installed | grep six
python-six - 1.12.0-r0

root@schlafzimmer-receiver:~# opkg list-upgradable | grep six
python-six - 1.12.0-r0 - 1.16.0-r0

root@schlafzimmer-receiver:~# opkg list-installed | grep fritz
enigma2-plugin-extensions-fritzcall - 99999:20221215-rev1631
```
```
Receiver
Marke & Modell:                     GI LX-3
Chipsatz (Frontprozessor-Version):  Broadcom 7424 (20038)
Hauptspeicher:                      858368 kB frei / 1154780 kB insgesamt
Receiver-Laufzeit:                  3d 13:57
Software
OE-System:                          OE-Alliance 4.4
Firmware-Version:                   OpenATV 6.4.20200528 (2020-05-28)
Kernel / Treiber:                   3.14.2 / 20160120
```
